import importlib.machinery
import importlib.util
import os
import shutil
import struct
import subprocess
import tempfile
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TESTDATA_DIR = PROJECT_ROOT / "testdata"
TEST_M4A = TESTDATA_DIR / "test.m4a"
# Rich-metadata fixture generated by testdata/regenerate.sh via ffmpeg.
# Contains: ©nam, ©ART, ©alb, ©day, ©too, ©cmt, ©gen, trkn iTunes tags.
TAGGED_M4A = TESTDATA_DIR / "tagged_tone.m4a"


# ---------------------------------------------------------------------------
# Minimal MP4 parser used by the "metadata preservation" tests.
# Locates the AAC sample byte ranges (from stbl) so we can prove every byte
# outside those ranges — i.e. all container metadata: ftyp, moov, udta, meta,
# ilst, stsd, chapter atoms, etc. — is byte-identical after gain adjustment.
# ---------------------------------------------------------------------------


def _find_box(buf, typ, start=0, end=None):
    if end is None:
        end = len(buf)
    off = start
    while off + 8 <= end:
        size = struct.unpack(">I", buf[off : off + 4])[0]
        t = buf[off + 4 : off + 8]
        header = 8
        if size == 1:
            size = struct.unpack(">Q", buf[off + 8 : off + 16])[0]
            header = 16
        elif size == 0:
            size = end - off
        if t == typ:
            return off, size, header
        off += size
    return None


def _top_level_boxes(buf):
    off = 0
    end = len(buf)
    while off + 8 <= end:
        size = struct.unpack(">I", buf[off : off + 4])[0]
        typ = buf[off + 4 : off + 8]
        header = 8
        if size == 1:
            if off + 16 > end:
                break
            size = struct.unpack(">Q", buf[off + 8 : off + 16])[0]
            header = 16
        elif size == 0:
            size = end - off

        if size < header or off + size > end:
            break

        yield off, typ, size, header
        off += size


def _parse_gain_metadata(buf):
    try:
        payload = _parse_itunes_tags(buf).get(b"M4AG")
    except TypeError:
        return None

    if not payload:
        return None

    fields = payload.decode("utf-8").split()
    if not fields or fields[0] != "m4againpy":
        return None

    metadata = {}
    for field in fields[1:]:
        if "=" in field:
            key, value = field.split("=", 1)
            metadata[key] = value
    return metadata


def _sample_byte_ranges(buf):
    """Return [(file_offset, size)] for every AAC sample in buf."""
    moov = _find_box(buf, b"moov")
    trak = _find_box(buf, b"trak", moov[0] + moov[2], moov[0] + moov[1])
    mdia = _find_box(buf, b"mdia", trak[0] + trak[2], trak[0] + trak[1])
    minf = _find_box(buf, b"minf", mdia[0] + mdia[2], mdia[0] + mdia[1])
    stbl = _find_box(buf, b"stbl", minf[0] + minf[2], minf[0] + minf[1])
    stbl_s, stbl_end = stbl[0] + stbl[2], stbl[0] + stbl[1]

    stsz = _find_box(buf, b"stsz", stbl_s, stbl_end)
    stsc = _find_box(buf, b"stsc", stbl_s, stbl_end)
    stco = _find_box(buf, b"stco", stbl_s, stbl_end)
    co64 = _find_box(buf, b"co64", stbl_s, stbl_end) if stco is None else None

    stsz_content = stsz[0] + stsz[2]
    default_size = struct.unpack(">I", buf[stsz_content + 4 : stsz_content + 8])[0]
    sample_count = struct.unpack(">I", buf[stsz_content + 8 : stsz_content + 12])[0]
    if default_size != 0:
        sizes = [default_size] * sample_count
    else:
        sizes_start = stsz_content + 12
        sizes = [
            struct.unpack(">I", buf[sizes_start + i * 4 : sizes_start + (i + 1) * 4])[0]
            for i in range(sample_count)
        ]

    stsc_content = stsc[0] + stsc[2]
    stsc_count = struct.unpack(">I", buf[stsc_content + 4 : stsc_content + 8])[0]
    stsc_entries = []
    for i in range(stsc_count):
        off = stsc_content + 8 + i * 12
        stsc_entries.append(
            (
                struct.unpack(">I", buf[off : off + 4])[0],
                struct.unpack(">I", buf[off + 4 : off + 8])[0],
            )
        )

    if stco is not None:
        chunk_content = stco[0] + stco[2]
        chunk_count = struct.unpack(">I", buf[chunk_content + 4 : chunk_content + 8])[0]
        chunk_offsets = [
            struct.unpack(">I", buf[chunk_content + 8 + i * 4 : chunk_content + 12 + i * 4])[0]
            for i in range(chunk_count)
        ]
    else:
        chunk_content = co64[0] + co64[2]
        chunk_count = struct.unpack(">I", buf[chunk_content + 4 : chunk_content + 8])[0]
        chunk_offsets = [
            struct.unpack(">Q", buf[chunk_content + 8 + i * 8 : chunk_content + 16 + i * 8])[0]
            for i in range(chunk_count)
        ]

    ranges = []
    sample_idx = 0
    for chunk_idx, chunk_off in enumerate(chunk_offsets):
        chunk_num = chunk_idx + 1
        spc = stsc_entries[0][1]
        for fc, s in stsc_entries:
            if fc <= chunk_num:
                spc = s
            else:
                break
        off_in_chunk = 0
        for _ in range(spc):
            if sample_idx >= sample_count:
                break
            size = sizes[sample_idx]
            ranges.append((chunk_off + off_in_chunk, size))
            off_in_chunk += size
            sample_idx += 1
    return ranges


def _redact_sample_bytes(buf):
    """Return a copy of buf with every AAC-sample byte zeroed, so container
    bytes (metadata, box headers, etc.) can be compared in isolation."""
    out = bytearray(buf)
    for off, size in _sample_byte_ranges(buf):
        for i in range(off, off + size):
            out[i] = 0
    return bytes(out)


def _find_ilst_blob(buf):
    """Return the raw bytes of the iTunes `ilst` box (including its header),
    or None if no ilst exists. Used to assert metadata round-trips exactly."""
    moov = _find_box(buf, b"moov")
    if moov is None:
        return None
    udta = _find_box(buf, b"udta", moov[0] + moov[2], moov[0] + moov[1])
    if udta is None:
        return None
    # meta has a 4-byte version/flags before its children
    meta = _find_box(buf, b"meta", udta[0] + udta[2], udta[0] + udta[1])
    if meta is None:
        return None
    ilst = _find_box(buf, b"ilst", meta[0] + meta[2] + 4, meta[0] + meta[1])
    if ilst is None:
        return None
    return bytes(buf[ilst[0] : ilst[0] + ilst[1]])


def _parse_itunes_tags(buf):
    """Walk moov/udta/meta/ilst/<name>/data and return {name: payload_bytes}."""
    moov = _find_box(buf, b"moov")
    if moov is None:
        return {}
    udta = _find_box(buf, b"udta", moov[0] + moov[2], moov[0] + moov[1])
    if udta is None:
        return {}
    meta = _find_box(buf, b"meta", udta[0] + udta[2], udta[0] + udta[1])
    if meta is None:
        return {}
    ilst = _find_box(buf, b"ilst", meta[0] + meta[2] + 4, meta[0] + meta[1])
    if ilst is None:
        return {}
    ilst_start = ilst[0] + ilst[2]
    ilst_end = ilst[0] + ilst[1]

    tags = {}
    off = ilst_start
    while off + 8 <= ilst_end:
        size = struct.unpack(">I", buf[off : off + 4])[0]
        name = bytes(buf[off + 4 : off + 8])
        data_box = _find_box(buf, b"data", off + 8, off + size)
        if data_box is not None:
            # data box header(8) + type(4) + locale(4) = 16 bytes before payload
            data_start = data_box[0] + 16
            data_end = data_box[0] + data_box[1]
            tags[name] = bytes(buf[data_start:data_end])
        off += size
    return tags


def _find_module():
    env = os.environ.get("M4AGAINPY_PYTHON_MODULE")
    if env:
        path = Path(env)
        if path.exists():
            return path
        raise FileNotFoundError(f"M4AGAINPY_PYTHON_MODULE points to a missing file: {path}")

    suffixes = list(importlib.machinery.EXTENSION_SUFFIXES)
    for fallback_suffix in (".so", ".dylib", ".pyd", ".dll"):
        if fallback_suffix not in suffixes:
            suffixes.append(fallback_suffix)

    candidates = []
    for target_dir in ("debug", "release"):
        for stem in ("libm4againpy", "m4againpy"):
            for suffix in suffixes:
                candidates.append(PROJECT_ROOT / "target" / target_dir / f"{stem}{suffix}")

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError(
        "Could not find the built m4againpy extension. "
        "Build it first with `cargo build --features python --lib` "
        "or `maturin develop --skip-install --features python`."
    )


def _load_module():
    path = _find_module()
    spec = importlib.util.spec_from_file_location("m4againpy", str(path))
    if spec is None or spec.loader is None:
        if path.suffix in {".dylib", ".dll"}:
            spec = importlib.util.spec_from_file_location(
                "m4againpy",
                str(path),
                loader=importlib.machinery.ExtensionFileLoader("m4againpy", str(path)),
            )

    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load m4againpy module from {path}")

    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


m4againpy = _load_module()


class M4aGainPyTest(unittest.TestCase):
    def test_gain_step_db_constant(self):
        self.assertEqual(m4againpy.GAIN_STEP_DB, 1.5)

    # -- bytes API --

    def test_bytes_zero_raises(self):
        data = TEST_M4A.read_bytes()
        with self.assertRaises(RuntimeError):
            m4againpy.aac_apply_gain(data, 0)

    def test_bytes_preserves_length(self):
        data = TEST_M4A.read_bytes()
        out = m4againpy.aac_apply_gain(data, 2)
        self.assertEqual(len(out), len(data))

    def test_bytes_positive_mutates(self):
        data = TEST_M4A.read_bytes()
        out = m4againpy.aac_apply_gain(data, 2)
        self.assertNotEqual(out, data)

    def test_bytes_negative_mutates(self):
        data = TEST_M4A.read_bytes()
        out = m4againpy.aac_apply_gain(data, -2)
        self.assertNotEqual(out, data)

    def test_bytes_inverse_round_trip(self):
        data = TEST_M4A.read_bytes()
        up = m4againpy.aac_apply_gain(data, 2)
        back = m4againpy.aac_apply_gain(up, -2)
        self.assertEqual(back, data)

    def test_bytes_not_m4a_raises(self):
        with self.assertRaises(RuntimeError):
            m4againpy.aac_apply_gain(b"\x00" * 128, 2)

    def test_bytes_returns_bytes_type(self):
        data = TEST_M4A.read_bytes()
        self.assertIsInstance(m4againpy.aac_apply_gain(data, 2), bytes)

    # -- file API --

    def test_file_zero_raises_and_does_not_create_dst(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            before = src.read_bytes()
            with self.assertRaises(RuntimeError):
                m4againpy.aac_apply_gain_file(str(src), str(dst), 0)
            self.assertFalse(dst.exists())
            self.assertEqual(src.read_bytes(), before)

    def test_file_rejects_same_src_dst_and_preserves_file(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            shutil.copy2(TEST_M4A, src)
            before = src.read_bytes()

            with self.assertRaises(RuntimeError):
                m4againpy.aac_apply_gain_file(str(src), str(src), 2)

            self.assertEqual(src.read_bytes(), before)

    def test_file_positive_writes_dst_and_preserves_src(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            original = src.read_bytes()

            modified = m4againpy.aac_apply_gain_file(str(src), str(dst), 2)
            self.assertGreater(modified, 0)

            self.assertTrue(dst.exists())
            dst_bytes = dst.read_bytes()
            self.assertGreater(len(dst_bytes), len(original))
            self.assertTrue(
                any(
                    dst_bytes[off : off + size] != original[off : off + size]
                    for off, size in _sample_byte_ranges(original)
                )
            )
            self.assertEqual(_parse_gain_metadata(dst_bytes)["gain_steps"], "2")
            # src must be untouched
            self.assertEqual(src.read_bytes(), original)

    def test_file_writes_gain_metadata_to_dst_only(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)

            m4againpy.aac_apply_gain_file(str(src), str(dst), -3)

            self.assertIsNone(_parse_gain_metadata(src.read_bytes()))
            metadata = _parse_gain_metadata(dst.read_bytes())
            self.assertEqual(metadata["version"], "1")
            self.assertEqual(metadata["gain_steps"], "-3")
            self.assertEqual(metadata["gain_step_db"], "1.5")

            probe = subprocess.run(
                [
                    "ffprobe",
                    "-hide_banner",
                    "-v",
                    "error",
                    "-show_entries",
                    "format_tags=M4AG",
                    "-of",
                    "default=nw=1",
                    "-export_all",
                    "1",
                    str(dst),
                ],
                check=True,
                stdout=subprocess.PIPE,
                text=True,
            )
            self.assertIn(
                "TAG:M4AG=m4againpy version=1 gain_steps=-3 gain_step_db=1.5",
                probe.stdout,
            )

    def test_file_src_preserved_on_negative_steps(self):
        """Second explicit check: negative gain also leaves src untouched."""
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            original = src.read_bytes()

            m4againpy.aac_apply_gain_file(str(src), str(dst), -3)
            self.assertEqual(src.read_bytes(), original)

    def test_file_nonexistent_raises(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            dst = Path(tmpdir) / "out.m4a"
            with self.assertRaises(RuntimeError):
                m4againpy.aac_apply_gain_file(
                    "/nonexistent/path/file.m4a", str(dst), 2
                )
            self.assertFalse(dst.exists())

    def test_file_non_m4a_raises(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            dst = Path(tmpdir) / "out.m4a"
            with self.assertRaises(RuntimeError):
                m4againpy.aac_apply_gain_file(
                    str(PROJECT_ROOT / ".gitignore"), str(dst), 2
                )
            self.assertFalse(dst.exists())


class MetadataPreservationTest(unittest.TestCase):
    """Prove that gain adjustment only touches bits inside AAC samples — every
    other byte in the MP4 container (ftyp, moov, stbl headers, udta, meta,
    ilst iTunes tags, chapter atoms, anything else) survives byte-for-byte."""

    def test_file_length_preserved(self):
        data = TEST_M4A.read_bytes()
        for steps in (-5, -2, -1, 1, 2, 5):
            self.assertEqual(len(m4againpy.aac_apply_gain(data, steps)), len(data))

    def test_container_bytes_outside_samples_unchanged_bytes_api(self):
        """Zero out all AAC-sample bytes, then the rest must match exactly."""
        data = TEST_M4A.read_bytes()
        redacted_original = _redact_sample_bytes(data)
        for steps in (-5, -2, -1, 1, 2, 5):
            out = m4againpy.aac_apply_gain(data, steps)
            redacted_out = _redact_sample_bytes(out)
            self.assertEqual(
                redacted_original,
                redacted_out,
                f"container bytes changed at gain_steps={steps}",
            )

    def test_file_api_adds_only_gain_metadata_to_itunes_tags(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "in.m4a"
            dst = Path(tmpdir) / "out.m4a"
            shutil.copy2(TEST_M4A, src)
            src_bytes = src.read_bytes()
            before_tags = _parse_itunes_tags(src_bytes)

            m4againpy.aac_apply_gain_file(str(src), str(dst), 3)

            # src untouched
            self.assertEqual(src.read_bytes(), src_bytes)

            after_tags = _parse_itunes_tags(dst.read_bytes())
            expected_tags = dict(before_tags)
            expected_tags[b"M4AG"] = b"m4againpy version=1 gain_steps=3 gain_step_db=1.5"
            self.assertEqual(after_tags, expected_tags)

    def test_file_api_preserves_existing_description_tag(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "described.m4a"
            dst = Path(tmpdir) / "described_out.m4a"
            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-y",
                    "-i",
                    str(TEST_M4A),
                    "-c",
                    "copy",
                    "-metadata",
                    "description=Existing description",
                    str(src),
                ],
                check=True,
            )
            before_tags = _parse_itunes_tags(src.read_bytes())
            self.assertEqual(before_tags.get(b"desc"), b"Existing description")

            m4againpy.aac_apply_gain_file(str(src), str(dst), 2)

            after_tags = _parse_itunes_tags(dst.read_bytes())
            self.assertEqual(after_tags.get(b"desc"), b"Existing description")
            self.assertEqual(
                after_tags.get(b"M4AG"),
                b"m4againpy version=1 gain_steps=2 gain_step_db=1.5",
            )

    def test_file_api_rewrites_chunk_offsets_when_moov_growth_moves_media(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "faststart.m4a"
            dst = Path(tmpdir) / "faststart_out.m4a"
            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-y",
                    "-i",
                    str(TEST_M4A),
                    "-c",
                    "copy",
                    "-movflags",
                    "faststart",
                    str(src),
                ],
                check=True,
            )

            src_bytes = src.read_bytes()
            src_moov = _find_box(src_bytes, b"moov")
            src_mdat = _find_box(src_bytes, b"mdat")
            self.assertIsNotNone(src_moov)
            self.assertIsNotNone(src_mdat)
            self.assertLess(src_moov[0], src_mdat[0])
            original_ranges = _sample_byte_ranges(src_bytes)

            modified = m4againpy.aac_apply_gain_file(str(src), str(dst), 2)
            self.assertGreater(modified, 0)

            dst_bytes = dst.read_bytes()
            dst_moov = _find_box(dst_bytes, b"moov")
            dst_mdat = _find_box(dst_bytes, b"mdat")
            self.assertIsNotNone(dst_moov)
            self.assertIsNotNone(dst_mdat)

            moov_growth = dst_moov[1] - src_moov[1]
            self.assertGreater(moov_growth, 0)
            self.assertEqual(dst_mdat[0], src_mdat[0] + moov_growth)

            rewritten_ranges = _sample_byte_ranges(dst_bytes)
            self.assertEqual(len(rewritten_ranges), len(original_ranges))
            for (before_off, before_size), (after_off, after_size) in zip(
                original_ranges, rewritten_ranges
            ):
                self.assertEqual(after_size, before_size)
                self.assertEqual(after_off, before_off + moov_growth)

    def test_sample_byte_ranges_unchanged(self):
        """stsz/stsc/stco values (sample sizes + chunk offsets) must not move."""
        data = TEST_M4A.read_bytes()
        original_ranges = _sample_byte_ranges(data)
        for steps in (-5, 2, 10):
            out = m4againpy.aac_apply_gain(data, steps)
            self.assertEqual(_sample_byte_ranges(out), original_ranges)

    def test_itunes_ilst_tag_preserved(self):
        """testdata/test.m4a ships with a `moov/udta/meta/ilst/©too` tag;
        its exact bytes must survive gain adjustment."""
        data = TEST_M4A.read_bytes()
        original_ilst = _find_ilst_blob(data)
        self.assertIsNotNone(original_ilst, "testdata should contain an ilst tag")
        # Sanity: the ilst contains at least one ©-prefixed atom
        self.assertIn(b"\xa9", original_ilst)

        for steps in (-3, 1, 4):
            out = m4againpy.aac_apply_gain(data, steps)
            self.assertEqual(_find_ilst_blob(out), original_ilst)

    def test_ftyp_preserved(self):
        """The first ftyp box (brand + compat list) must be untouched."""
        data = TEST_M4A.read_bytes()
        ftyp = _find_box(data, b"ftyp")
        self.assertIsNotNone(ftyp)
        original_ftyp = data[ftyp[0] : ftyp[0] + ftyp[1]]

        for steps in (-3, 2):
            out = m4againpy.aac_apply_gain(data, steps)
            ftyp_out = _find_box(out, b"ftyp")
            self.assertEqual(out[ftyp_out[0] : ftyp_out[0] + ftyp_out[1]], original_ftyp)


class ShortWindowAacTest(unittest.TestCase):
    def test_file_api_patches_short_window_stereo_frames_and_ffmpeg_decodes(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "short_window.m4a"
            dst = Path(tmpdir) / "short_window_gain.m4a"

            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-y",
                    "-f",
                    "lavfi",
                    "-i",
                    (
                        "aevalsrc="
                        "'if(lt(mod(t,0.25),0.018),0.95*sin(2*PI*2800*t),0.04*sin(2*PI*440*t))|"
                        "if(lt(mod(t,0.25),0.018),0.95*sin(2*PI*3600*t),0.04*sin(2*PI*660*t))'"
                        ":s=32000:d=3"
                    ),
                    "-c:a",
                    "aac",
                    "-b:a",
                    "96k",
                    str(src),
                ],
                check=True,
            )

            sample_count = len(_sample_byte_ranges(src.read_bytes()))
            modified = m4againpy.aac_apply_gain_file(str(src), str(dst), 5)
            self.assertEqual(modified, sample_count * 2)

            subprocess.run(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-nostdin",
                    "-v",
                    "error",
                    "-i",
                    str(dst),
                    "-f",
                    "null",
                    "-",
                ],
                check=True,
            )


class TaggedFixtureTest(unittest.TestCase):
    """Same guarantees as MetadataPreservationTest, but exercised against an
    ffmpeg-generated fixture with 8 iTunes tags (title, artist, album, date,
    encoder, comment, genre, track) — richer than the bundled test.m4a.

    The fixture is committed under testdata/; if it's missing, tests fail
    loudly rather than skipping. Regenerate with testdata/regenerate.sh."""

    EXPECTED_TAGS = {
        b"\xa9nam": b"Gain Test Tone",
        b"\xa9ART": b"m4againpy",
        b"\xa9alb": b"Fixtures",
        b"\xa9day": b"2026",
        b"\xa9gen": b"Electronic",
        b"\xa9cmt": b"Used to verify metadata survives gain adjustment.",
        # ©too (encoder) is set by ffmpeg and version-dependent (e.g.
        # "Lavf61.7.100"); we only assert it's present and round-trips.
        # trkn has binary packed bytes; likewise — checked via round-trip.
    }

    def test_fixture_has_expected_tags(self):
        tags = _parse_itunes_tags(TAGGED_M4A.read_bytes())
        for name, value in self.EXPECTED_TAGS.items():
            self.assertEqual(tags.get(name), value, f"{name!r} missing or wrong")
        self.assertIn(b"\xa9too", tags)
        self.assertIn(b"trkn", tags)

    def test_tags_preserved_after_gain(self):
        data = TAGGED_M4A.read_bytes()
        before = _parse_itunes_tags(data)
        for steps in (-5, -2, 1, 3, 8):
            out = m4againpy.aac_apply_gain(data, steps)
            after = _parse_itunes_tags(out)
            self.assertEqual(before, after, f"tags changed at gain_steps={steps}")

    def test_container_bytes_outside_samples_unchanged(self):
        """Byte-exact structural preservation on the rich-metadata fixture."""
        data = TAGGED_M4A.read_bytes()
        redacted_original = _redact_sample_bytes(data)
        for steps in (-3, 2, 7):
            out = m4againpy.aac_apply_gain(data, steps)
            self.assertEqual(_redact_sample_bytes(out), redacted_original)

    def test_ilst_blob_identical_after_gain(self):
        data = TAGGED_M4A.read_bytes()
        original_ilst = _find_ilst_blob(data)
        self.assertIsNotNone(original_ilst)
        for steps in (-3, 2, 7):
            out = m4againpy.aac_apply_gain(data, steps)
            self.assertEqual(_find_ilst_blob(out), original_ilst)

    def test_file_api_preserves_tags_and_adds_custom_gain_tag(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            src = Path(tmpdir) / "tagged.m4a"
            dst = Path(tmpdir) / "tagged_out.m4a"
            shutil.copy2(TAGGED_M4A, src)
            src_original = src.read_bytes()
            before = _parse_itunes_tags(src_original)

            modified = m4againpy.aac_apply_gain_file(str(src), str(dst), 4)
            self.assertGreater(modified, 0)

            # src untouched
            self.assertEqual(src.read_bytes(), src_original)
            # dst preserves existing tags and adds ffprobe-visible gain metadata
            after = _parse_itunes_tags(dst.read_bytes())
            expected = dict(before)
            expected[b"M4AG"] = b"m4againpy version=1 gain_steps=4 gain_step_db=1.5"
            self.assertEqual(expected, after)

    def test_gain_actually_applied_on_fixture(self):
        """Sanity: ensure the fixture has non-silent samples so the gain test
        isn't trivially passing on all-zeroed gain locations."""
        data = TAGGED_M4A.read_bytes()
        out = m4againpy.aac_apply_gain(data, 3)
        self.assertNotEqual(out, data)


if __name__ == "__main__":
    unittest.main()
